# Generated by Django 4.2.7 on 2025-12-31 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(unique=True)),
                ('courier_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ON_THE_WAY', 'On The Way'), ('DELIVERED', 'Delivered')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deliveries',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
